# Generated by Django 4.2.6 on 2023-11-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=200)),
                ('CarDesc', models.CharField(max_length=200)),
                ('CarPrice', models.BigIntegerField()),
                ('CarImage', models.CharField(default='https://shop.roadster.com/assets/car-placeholder-652ae305f4b4afc9eb5f2d976fa0f77979069acb686b0a16fcc062e210367660.png', max_length=500)),
            ],
        ),
    ]
